
#!/usr/bin/env python
# -*- coding: utf-8 -*-

##########################################
## NOTE: This module was autogenerated. ##
## Contains no user-servicable parts!!! ##
##########################################

import unittest

from inflex import Adjective


class TestAdjectiveToSingular(unittest.TestCase):
    '''
    test_args has the format [
        {
            "in":     ..., # (required)
            "out":    ..., # (required)
            "desc":   ..., # (optional)
            "kwargs": ...  # (optional)
        }, ...
    ]
    '''
    test_args = [
        {'in': 'My', 'out': 'My'},
        {'in': 'Our', 'out': 'My'},
        {'in': 'Some', 'out': 'A'},
        {'in': 'That', 'out': 'That'},
        {'in': 'Their', 'out': 'Their'},
        {'in': 'These', 'out': 'This'},
        {'in': 'This', 'out': 'This'},
        {'in': 'Those', 'out': 'That'},
        {'in': 'Your', 'out': 'Your'},
        {'in': 'a', 'out': 'a'},
        {'in': 'my', 'out': 'my'},
        {'in': 'our', 'out': 'my'},
        {'in': 'some', 'out': 'a'},
        {'in': 'that', 'out': 'that'},
        {'in': 'their', 'out': 'their'},
        {'in': 'these', 'out': 'this'},
        {'in': 'this', 'out': 'this'},
        {'in': 'those', 'out': 'that'},
        {'in': 'your', 'out': 'your'},
    ]

    def test_adjective_to_singular(self):
        for test_case in self.test_args:
            with self.subTest():
                # Expand test_case with default cases, if optional keys are not provided
                test_case = {**test_case, **{
                    "desc": f"singular({repr(test_case['in'])}) => {repr(test_case['out'])}",
                    "kwargs": dict()
                }}
                self.assertEqual(Adjective(test_case["in"]).singular(**test_case["kwargs"]), test_case["out"], test_case["desc"])


if __name__ == "__main__":
    unittest.main()
