
#!/usr/bin/env python
# -*- coding: utf-8 -*-

##########################################
## NOTE: This module was autogenerated. ##
## Contains no user-servicable parts!!! ##
##########################################

import unittest

from inflexion.adjective_core import convert_to_plural

class TestAdjectiveToPlural(unittest.TestCase):
    # test_args has the format [{
    #    "in":     ..., # (required)
    #    "out":    ..., # (required)
    #    "desc":   ..., # (optional) 
    #    "kwargs": ...  # (optional)
    # }, ...
    # ]
    test_args = [
        {'in': 'a', 'out': 'some'},
        {'in': 'an', 'out': 'some'},
        {'in': 'her', 'out': 'their'},
        {'in': 'his', 'out': 'their'},
        {'in': 'its', 'out': 'their'},
        {'in': 'my', 'out': 'our'},
        {'in': 'our', 'out': 'our'},
        {'in': 'some', 'out': 'some'},
        {'in': 'that', 'out': 'those'},
        {'in': 'their', 'out': 'their'},
        {'in': 'these', 'out': 'these'},
        {'in': 'this', 'out': 'these'},
        {'in': 'those', 'out': 'those'},
        {'in': 'your', 'out': 'your'},
    ]

    def test_convert_to_plural(self):
        for test_case in self.test_args:
            with self.subTest():
                # Expand test_case with default cases, if optional keys are not provided
                test_case = {**test_case, **{
                    "desc": f"convert_to_plural({repr(test_case['in'])}) => {repr(test_case['out'])}",
                    "kwargs": dict()
                }}
                self.assertEqual(convert_to_plural(test_case["in"], **test_case["kwargs"]), test_case["out"], test_case["desc"])

if __name__ == "__main__":
    unittest.main()
