name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Inflex
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: ${{ env.pythonLocation }}
          key: python-dependencies-${{ hashFiles('requirements.txt') }}-${{ hashFiles('docs/requirements.txt') }}-${{ env.pythonLocation }}

      - name: Install dependencies on cache miss
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r docs/requirements.txt
        if: steps.restore-cache.outputs.cache-hit != 'true'

      - name: Build Sphinx
        run: python -m sphinx -Ea docs build

      - name: Deploy Sphinx
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
