name: pre-commit

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
    - name: Run all tests for all supported Python versions, and display test coverage
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        tox